/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'jphoenix' at '7/28/16 4:12 PM' with Gradle 2.14
 *
 * @author jphoenix, @date 7/28/16 4:12 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
